### ISSUE TITLE
Xiaomi 4 Ultra Zero Start

### ISSUE THREAD

**Issue by Jupoma** [scooterteam/bw-patcher#2]
Offset 0x00004396 for Zero Start

0xbb = Lower Start Speed 1kmh  (Zero Start)
0x49 = Normal Start Speed
![image](https://github.com/user-attachments/assets/a393ce18-c8dd-4962-bedb-c24f67a19e50)

![image](https://github.com/user-attachments/assets/85d50c6d-81f8-45d2-80e6-a9d96e3be502)

**Comment by Jupoma** [comment]
![image](https://github.com/user-attachments/assets/9680fcf6-c0ce-47a5-be12-a89489ca3cea)
![image](https://github.com/user-attachments/assets/bb2c760b-c9ff-4555-bbf7-8fb9b7ea8bcb)

Unfortunately only for version 0015 the offsets for the start speeds.

I did not search for the offset for the start speed for version 0018.

**Comment by encryptize** [comment]
Thanks. The patch works with any firmware version.

https://github.com/scooterteam/bw-patcher/commit/f3bab2bb41841c0b11eecfc9853b8d777a79ec36
